name: hadolint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
    - name: "hadolint: elixir"
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: ./elixir/Dockerfile
